project:
  type: website
  output-dir: .

website:
  title: "PHYS 409"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://phys409.github.io/Winter2025/
        text: "Winter 2025" 
        target: _blank #makes it open in new page
      - href: https://phys409.github.io/Winter2026/
        text: "Winter 2026" 
        target: _blank #makes it open in new page

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
self-contained: true


